# Generated by Django 2.0.13 on 2020-03-31 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='nickname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
