# Generated by Django 2.0.13 on 2020-03-31 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_student_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='certified',
        ),
    ]
