# Generated by Django 3.0.4 on 2020-04-02 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # ('auth', '0011_update_proxy_permissions'),
        ('user', '0005_auto_20200402_2258'),
        ('community', '0008_auto_20200402_2258'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AddField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
