# Generated by Django 3.0.4 on 2020-03-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='available_number',
            field=models.CharField(max_length=50),
        ),
    ]
