# Generated by Django 3.0.4 on 2020-03-16 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0003_auto_20200316_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='available_number',
            field=models.CharField(max_length=100),
        ),
    ]
