# Generated by Django 3.0.4 on 2020-03-16 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0004_auto_20200316_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='language_condition',
            field=models.CharField(max_length=500),
        ),
    ]
