# Generated by Django 3.0.4 on 2020-03-16 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0009_auto_20200316_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='major',
            field=models.CharField(max_length=40),
        ),
    ]
