# Generated by Django 3.0.4 on 2020-03-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0013_auto_20200316_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='ex_period',
            field=models.CharField(max_length=40),
        ),
    ]
