# Generated by Django 3.0.4 on 2020-03-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0014_auto_20200316_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='dorm_satisfaction',
            field=models.CharField(max_length=100),
        ),
    ]
