# Generated by Django 3.0.4 on 2020-03-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0015_auto_20200316_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='dorm_cost',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='report',
            name='dorm_satisfaction',
            field=models.CharField(max_length=30),
        ),
    ]
