# Generated by Django 3.0.4 on 2020-03-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0017_auto_20200316_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='dorm_location',
            field=models.CharField(max_length=100),
        ),
    ]
