# Generated by Django 2.0.13 on 2020-03-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0018_auto_20200316_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='student_id',
            field=models.CharField(max_length=30),
        ),
    ]
