# Generated by Django 3.0.4 on 2020-03-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0019_auto_20200317_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='remarks',
        ),
        migrations.AddField(
            model_name='university',
            name='course_restriction',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='image_url',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='not_major_course',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='one_year_available',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='satisfaction',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='went_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='language_condition',
            field=models.TextField(),
        ),
    ]
