# Generated by Django 3.0.4 on 2020-03-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0020_auto_20200323_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='course_restriction',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='not_major_course',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='one_year_available',
            field=models.TextField(null=True),
        ),
    ]
