# Generated by Django 3.0.4 on 2020-03-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0021_auto_20200323_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='image_url',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
