# Generated by Django 3.0.4 on 2020-03-24 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0022_auto_20200323_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='remarks',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='went_major',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
