# Generated by Django 3.0.4 on 2020-03-24 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0023_auto_20200324_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='remarks',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
