# Generated by Django 3.0.4 on 2020-03-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='date',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='no',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='url',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
