# Generated by Django 3.0.4 on 2020-03-23 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_auto_20200323_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
