# Generated by Django 2.0.13 on 2020-03-31 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_auto_20200331_1413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='nation',
            new_name='tag',
        ),
    ]
