# Generated by Django 2.0.13 on 2020-03-31 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_auto_20200331_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='nation',
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
